---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# MMP

<!-- badges: start -->
<!-- badges: end -->

The goal of MMP is to conduct the multi-modalities radiomics phenotype analysis, which mostly based on the MOVICS package. 

## Installation

You can install the development version of MMP from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("yzhizai/MMP")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(tidyverse)
library(MOVICS)
library(umap)
library(class)
library(MMP)

flist <- c('feature_static_all.csv',
           'feature_dynamic_all.csv')
src.info <- read_csv('data_from_source.csv')

dt.list.train <- getDatalist(flist, which(src.info$Source == 0))
dt.list.test <- getDatalist(flist, which(src.info$Source == 1))
# dimension reduction.
clust.data <- DR_umap(dt.list.train = dt.list.train, dt.list.test = dt.list.test)

# clustering analysis
cmoic.clust <- clust_identify(clust.data[[1]])

# predict the cluster
test.pred <- knn_train_test(cmoic.clust,
               clust.data.train = clust.data[[1]],
               clust.data.test = clust.data[[2]])
src.info$Group <- 0
src.info$Group[src.info$Source == 0] <- cmoic.clust$clust.res$clust
src.info$Group[src.info$Source == 1] <- test.pred

out.clust <- data.frame(samID = paste0('subj', 1:length(test.pred)),
                    clust = test.pred)

write_csv(src.info, 'grp_info.csv')

out.clust.validation <- out.clust %>% slice(which(src.info$Source == 1)) %>%
  as.data.frame
rownames(out.clust.validation) <- out.clust.validation$samID

clust.data.2 <- clust.data[[2]]
draw_Heatmap(clust.data.2, out.clust.validation, fig.name = 'Heatmap')
```
